version: '2.1'

services:
  dev:
    build: .
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    command: python worker.py

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    links:
      - devss
